package wxpay

//应用场景
//当商户申请的退款有结果后，微信会把相关结果发送给商户，商户需要接收处理，并返回应答。
//对后台通知交互时，如果微信收到商户的应答不是成功或超时，微信认为通知失败，微信会通过一定的策略定期重新发起通知，尽可能提高通知的成功率，但微信不保证通知最终能成功。 （通知频率为15/15/30/180/1800/1800/1800/1800/3600，单位：秒）
//注意：同样的通知可能会多次发送给商户系统。商户系统必须能够正确处理重复的通知。
//推荐的做法是，当收到通知进行处理时，首先检查对应业务数据的状态，判断该通知是否已经处理过，如果没有处理过再进行处理，如果处理过直接返回结果成功。在对业务数据进行状态检查和处理之前，要采用数据锁进行并发控制，以避免函数重入造成的数据混乱。
//特别说明：退款结果对重要的数据进行了加密，商户需要用商户证书与商户秘钥进行解密后才能获得结果通知的内容
//解密方式
//解密步骤如下：
//（1）对加密串A做base64解码，得到加密串B
//（2）对商户key做md5，得到32位小写key* ( key设置路径：微信商户平台(pay.weixin.qq.com)-->账户设置-->API安全-->密钥设置 )
//（3）用key*对加密串B做AES-256-ECB解密
//接口链接
//开通该功能需要在商户平台-交易中心-退款配置中配置notify_url。
//如果链接无法访问，商户将无法接收到微信通知。
//通知url必须为直接可访问的url，不能携带参数。示例：notify_url：“https://pay.weixin.qq.com/wxpay/pay.action”
//通知参数
//
//字段名
//变量名
//必填
//类型
//示例值
//描述
//返回状态码
//return_code
//是
//String(16)
//SUCCESS
//SUCCESS/FAIL
//此字段是通信标识，非结果标识，退款是否成功需要解密后查看refund_status 来判断
//返回信息
//return_msg
//否
//String(128)
//返回信息，如非空，为错误原因
//参数格式校验错误
//以下字段在return_code为SUCCESS的时候有返回：
//
//字段名
//变量名
//必填
//类型
//示例值
//描述
//公众账号ID
//appid
//是
//String(32)
//wx8888888888888888
//微信分配的公众账号ID（企业号corpid即为此appId）
//退款的商户号
//mch_id
//是
//String(32)
//1900000109
//微信支付分配的商户号
//随机字符串
//nonce_str
//是
//String(32)
//5K8264ILTKCH16CQ2502SI8ZNMTM67VS
//随机字符串，不长于32位。推荐随机数生成算法
//加密信息
//req_info
//是
//String(1024)
//加密信息请用商户证书与商户秘钥进行解密
//以下为返回的加密字段：
//
//字段名
//变量名
//必填
//类型
//示例值
//描述
//微信订单号
//transaction_id
//是
//String(32)
//1217752501201407033233368018
//微信订单号
//商户订单号
//out_trade_no
//是
//String(32)
//1217752501201407033233368018
//商户系统内部的订单号
//微信退款单号
//refund_id
//是
//String(28)
//1217752501201407033233368018
//微信退款单号
//商户退款单号
//out_refund_no
//是
//String(64)
//1217752501201407033233368018
//商户退款单号
//订单金额
//total_fee
//是
//Int
//100
//订单总金额，单位为分，只能为整数，详见支付金额
//应结订单金额
//settlement_total_fee
//否
//Int
//100
//当该订单有使用非充值券时，返回此字段。应结订单金额=订单金额-非充值代金券金额，应结订单金额<=订单金额。
//申请退款金额
//refund_fee
//是
//Int
//100
//退款总金额,单位为分
//退款金额
//settlement_refund_fee
//是
//Int
//100
//退款金额=申请退款金额-非充值代金券退款金额，退款金额<=申请退款金额
//退款状态
//refund_status
//是
//String(16)
//SUCCESS
//SUCCESS-退款成功
//CHANGE-退款异常
//REFUNDCLOSE—退款关闭
//退款成功时间
//success_time
//否
//String(20)
//20160725152626
//-
//退款入账账户
//refund_recv_accout
//是
//String(64)
//招商银行信用卡0403
//取当前退款单的退款入账方
//1）退回银行卡：
//{银行名称}{卡类型}{卡尾号}
//2）退回支付用户零钱:
//支付用户零钱
//3）退还商户:
//商户基本账户
//商户结算银行账户
//4）退回支付用户零钱通:
//支付用户零钱通
//退款资金来源
//refund_account
//是
//String(30)
//REFUND_SOURCE_RECHARGE_FUNDS
//REFUND_SOURCE_RECHARGE_FUNDS 可用余额退款/基本账户
//REFUND_SOURCE_UNSETTLED_FUNDS 未结算资金退款
//退款发起来源
//refund_request_source
//是
//String(30)
//API
//API接口
//VENDOR_PLATFORM商户平台
//举例如下：
//<xml>
//<return_code>SUCCESS</return_code>
//<appid><![CDATA[wx2421b1c4370ec43b]]></appid>
//<mch_id><![CDATA[10000100]]></mch_id>
//<nonce_str><![CDATA[TeqClE3i0mvn3DrK]]></nonce_str>
//<req_info><![CDATA[T87GAHG17TGAHG1TGHAHAHA1Y1CIOA9UGJH1GAHV871HAGAGQYQQPOOJMXNBCXBVNMNMAJAA]]></req_info>
//</xml>
//返回参数
//商户处理退款通知参数后同步返回给微信参数：
//
//字段名
//变量名
//必填
//类型
//示例值
//描述
//返回状态码
//return_code
//是
//String(16)
//SUCCESS
//SUCCESS/FAIL
//SUCCESS表示商户接收通知成功并校验成功
//返回信息
//return_msg
//否
//String(128)
//OK
//返回信息，如非空，为错误原因
//参数格式校验错误
//举例如下：
//<xml>
//<return_code><![CDATA[SUCCESS]]></return_code>
//<return_msg><![CDATA[OK]]></return_msg>
//</xml>
